metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "8a2aa2e6e066673108c3135b7bf68c1193b30fbc26cebd16d4317a9c58b555b0"


[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "9a1b57b22ff44ad8bd8e08e2b1695b627cc77a3964443fe02ae903ffac4c"
metrics_token = "484961a4b68a15f9a31c410d3237389becfb2ec8f6a7d7556f84182f2073"
